config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'
  get '/about' => 'page#about'
  get '/signup' => 'users#signup', :as => "signup"
  get '/login' => 'users#login', :as => "login"
  post 'create_login_session' => 'users#create_login_session'
  delete 'logout' => 'users#logout', :as => "logout"

  resources :issues

  post '/issues/:issue_id/comments' => 'comments#create'

  resources :users, only: [:create]

  resources :comments, only: [:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :user
  belongs_to :issue

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many   :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :comments
	has_many :issues

	validates :name, :email, presence: true
	validates :name, :email, uniqueness: { case_sensitive: false }

	has_secure_password

	before_create { generate_token(:auth_token) }

	def avatar
  	gravatar_id = Digest::MD5.hexdigest(self.email.downcase) if self.email
  	"http://gravatar.com/avatar/#{gravatar_id}.png?s=512&d=retro"
	end

	def generate_token(column)
	  begin
	    self[column] = SecureRandom.urlsafe_base64
	  end while User.exists?(column => self[column])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
	
	helper_method :current_user

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@comment = Comment.new(comment_params)
    @comment.save
    respond_to do |format|
    	format.js
    end
  end

  private
  	def comment_params
  		params.require(:comment).permit(:issue_id, :user_id, :content)
  	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
     @issue = Issue.find(params[:id])
     @comments = @issue.comments
  end

  def new
    if not current_user
      flash[:notice] = "没有执行此操作的权限，请先登录"
      redirect_to :root
      return
    else
      @issue = Issue.new
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def create
    Issue.create(issue_params)
    redirect_to :root
  end

  def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to :root
  end

  def destroy
    i = Issue.find(params[:id])
    i.destroy
    redirect_to :root
  end

  private
    def issue_params
      params.require(:issue).permit(:title, :content, :user_id)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def welcome
    @issues  = Issue.all.reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      UserMailer.welcome_email(@user).deliver
  		cookies[:auth_token] = @user.auth_token
  		redirect_to :root
  	else
  		render :signup
  	end
  end

  def login
  end

  def create_login_session
  	user = User.find_by_name(params[:name])
  	if user && user.authenticate(params[:password])
  		if params[:remember_me]
  			cookies.permanent[:auth_token] = user.auth_token
  		else
  			cookies[:auth_token] = user.auth_token
  		end
  		flash.notice = "登陆成功！"
  		redirect_to :root
  	else
  		flash.notice = "用户名密码错误!"
  		redirect_to :login
  	end
  end

  def logout
  	cookies.delete(:auth_token)
  	redirect_to :root
  end

  private
  	def user_params
  		params.require(:user).permit!
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	class HTMLwithPygments < Redcarpet::Render::HTML
	  def block_code(code, language)
	    Pygments.highlight(code, lexer: language)
	  end
	end

	def markdown(text)
	  renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
	  options = {
	    autolink: true,
	    no_intra_emphasis: true,
	    fenced_code_blocks: true,
	    lax_html_blocks: true,
	    strikethrough: true,
	    superscript: true
	  }
	  Redcarpet::Markdown.new(renderer, options).render(text).html_safe
	end

end

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render partial: 'form', locals: {issue: @issue} %>

app/views/issues/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for(Issue.new(user_id: current_user.id)) do |f| %>
    	<%= f.hidden_field :user_id %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <% if current_user && current_user == @issue.user %>
      <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <%= image_tag @issue.user.avatar, class: "image-circle" %>
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><%= link_to @issue.user.name %></h5>
        </div>
        <%= markdown(@issue.content) %>
      </div>
    </article>
    <% @comments.each do |c| %>
      <%= render partial: 'shared/comment', locals: {c: c} %>
    <% end %>
  </div>
  <% if current_user %>
    <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
  <% else %>
    <%= link_to "登录发评论", login_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Running</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
  <div class="navbar clearfix">
    <div class="container">
      <a class="navbar-brand" href="/">
        奔跑吧
      </a>
      <ul class="nav right">        
        <% if current_user %>
          <li><%= link_to current_user.name, "#" %></li>
          <li><%= link_to t("navbar.logout"), logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to t("navbar.login"), login_path %></li>     
          <li><%= link_to t("navbar.signup"), signup_path %></li>
        <% end %>
          <li><%= link_to t("navbar.about"), "/about" %></li>
      </ul>
    </div>
  </div>

  <% if flash.notice %>
    <div class="notice"><%= flash.notice %></div>
  <% end %>

  <%= yield %>

  <div class="footer">
    <div class="container">
      Copyright © 2015 <a href="http://www.wangyzyoga.com" rel="nofollow">WangYaojia
    </div>
  </div>
  <script>
    $('.home-banner').anystretch();
  </script>

  <script>
    $('.home-banner').anystretch();
    var hideNotice = function(){
      $(".notice").fadeOut("slow");
    }
    setTimeout(hideNotice, 4000);
  </script>

</body>
</html>

app/views/page/_issue_list.html.erb
<div class="issue-list">
  <% issues.each do |i| %>
    <article class="issue clearfix">
      <div class="avatar">
        <%= link_to "#" do %>
          <%= image_tag i.user.avatar %>
        <% end %>
      </div>
      <div class="body">
        <h5 class="title">
          <%= link_to i.title, issue_path(i) %>
        </h5>
        <a class="read-more" href="#">read</a>
        <span class="meta-data">
          <%= link_to i.user.name, '#' %>
          <%= time_ago_in_words(i.created_at) %> ago
        </span>
      </div>
      <div class="issue-comment-count">
        <i class="fa fa-comments icon-muted"></i>
        <%= link_to i.comments.count, i %>
      </div>
    </article>
  <% end %>
</div>

app/views/page/about.html.erb
  <div class="container">
    <h1>about </h1>
  </div>

app/views/page/welcome.html.erb
<div class="home-banner" data-stretch="<%= image_url "home-banner-bg.jpg" %>">
  <div class="banner-inner container clearfix">
    <h1>Are you ready?</h1>
    <div class="home-banner-links">
      <%= link_to "发起新挑战", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">所有活动都在下面...</h1>
  </div>
</div>

<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>


<script>
  $('.home-banner').anystretch();
</script>

app/views/shared/_comment.html.erb
    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag c.user.avatar, class: 'image-circle' %>

       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.user.name, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> ago
            </span>
         </div>
         <%= markdown(c.content) %>
       </div>
    </div>
  <% end %>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
      <img src=<%= current_user.avatar %> alt="" class="image-circle">
    <% end %>
  </div>
  <div class="body">
    <%= form_for(Comment.new(:issue_id => issue.id, :user_id => current_user.id), remote: true) do |f| %>
      <%= f.hidden_field :issue_id %>
      <%= f.hidden_field :user_id  %>
      <%= f.text_area :content %>
      <%= submit_tag '提交评论', class: 'btn btn-primary btn-submit' %>
    <% end %>
  </div>
</article>

<script>
  var commenter_exist = [];
  $('.reply .name a').each(function() {
    if($.inArray($(this).text(), commenter_exist) < 0) {
      commenter_exist.push($(this).text());
    }
  });
  $('textarea').atwho({ at: "@", 'data': commenter_exist });
</script>

<script>
  $(".reply textarea#comment_content").keydown(function(e) {
    if ((e.ctrlKey||e.metaKey) && e.keyCode == 13) {
      $(".reply input[type=submit]").click();
    }
  });
</script>

app/views/users/login.html.erb
<div class="login-form-container clearfix">
  <div class="login-form">
    <%= form_tag "/create_login_session" do %>
      <dl class="form">
        <dt>
          <%= label_tag "用户名" %>
        </dt>
        <dd>
          <%= text_field_tag :name, params[:name] %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
          <%= label_tag "密码" %>
        </dt>
        <dd>
          <%= password_field_tag :password, params[:password] %>
        </dd>
      </dl>
      <dl class="form remember-me">
        <%= check_box_tag :remember_me, 1, params[:remember_me] %>
        <%= label_tag :remember_me %>
      </dl>
      <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
      <div class="need-signup">
        <%= link_to "没有账号？注册一个吧", signup_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
  <div class="signup-form">
    <%= form_for @user do |f| %>
        <dl class="form">
          <dt><%= f.label :name, "用户名" %></dt>
          <dd><%= f.text_field :name %></dd>
          <% if @user.errors[:name].any? %>
            <dd class="error"><%= @user.errors[:name][0] %></dd>
          <% end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :email %></dt>
          <dd><%= f.text_field :email %></dd>
          <% if @user.errors[:email].any? %>
            <dd class="error"><%= @user.errors[:email][0] %></dd>
          <% end %>          
        </dl>
        <dl class="form">
          <dt><%= f.label :password, "密码" %></dt>
          <dd><%= f.password_field :password %></dd>
          <% if @user.errors[:password].any? %>
            <dd class="error"><%= @user.errors[:password][0] %></dd>
          <% end %>          
        </dl>
        <dl class="form">
          <dt><%= f.label :password_confirmation, "请再输入一次" %></dt>
          <dd><%= f.password_field :password_confirmation %></dd>
          <% if @user.errors[:password_confirmation].any? %>
            <dd class="error"><%= @user.errors[:password_confirmation][0] %></dd>
          <% end %>          
        </dl>
        <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>